// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands/common.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Instance struct {
	// The ID of the instance.
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Instance) Reset()         { *m = Instance{} }
func (m *Instance) String() string { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()    {}
func (*Instance) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b273be58978a133, []int{0}
}

func (m *Instance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instance.Unmarshal(m, b)
}
func (m *Instance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instance.Marshal(b, m, deterministic)
}
func (m *Instance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instance.Merge(m, src)
}
func (m *Instance) XXX_Size() int {
	return xxx_messageInfo_Instance.Size(m)
}
func (m *Instance) XXX_DiscardUnknown() {
	xxx_messageInfo_Instance.DiscardUnknown(m)
}

var xxx_messageInfo_Instance proto.InternalMessageInfo

func (m *Instance) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DownloadProgress struct {
	// URL of the download.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// The file being downloaded.
	File string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	// Total size of the file being downloaded.
	TotalSize int64 `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	// Size of the downloaded portion of the file.
	Downloaded int64 `protobuf:"varint,4,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	// Whether the download is complete.
	Completed            bool     `protobuf:"varint,5,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadProgress) Reset()         { *m = DownloadProgress{} }
func (m *DownloadProgress) String() string { return proto.CompactTextString(m) }
func (*DownloadProgress) ProtoMessage()    {}
func (*DownloadProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b273be58978a133, []int{1}
}

func (m *DownloadProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadProgress.Unmarshal(m, b)
}
func (m *DownloadProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadProgress.Marshal(b, m, deterministic)
}
func (m *DownloadProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadProgress.Merge(m, src)
}
func (m *DownloadProgress) XXX_Size() int {
	return xxx_messageInfo_DownloadProgress.Size(m)
}
func (m *DownloadProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadProgress.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadProgress proto.InternalMessageInfo

func (m *DownloadProgress) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DownloadProgress) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

func (m *DownloadProgress) GetTotalSize() int64 {
	if m != nil {
		return m.TotalSize
	}
	return 0
}

func (m *DownloadProgress) GetDownloaded() int64 {
	if m != nil {
		return m.Downloaded
	}
	return 0
}

func (m *DownloadProgress) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type TaskProgress struct {
	// Description of the task.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Additional information about the task.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Whether the task is complete.
	Completed            bool     `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskProgress) Reset()         { *m = TaskProgress{} }
func (m *TaskProgress) String() string { return proto.CompactTextString(m) }
func (*TaskProgress) ProtoMessage()    {}
func (*TaskProgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b273be58978a133, []int{2}
}

func (m *TaskProgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskProgress.Unmarshal(m, b)
}
func (m *TaskProgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskProgress.Marshal(b, m, deterministic)
}
func (m *TaskProgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskProgress.Merge(m, src)
}
func (m *TaskProgress) XXX_Size() int {
	return xxx_messageInfo_TaskProgress.Size(m)
}
func (m *TaskProgress) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskProgress.DiscardUnknown(m)
}

var xxx_messageInfo_TaskProgress proto.InternalMessageInfo

func (m *TaskProgress) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskProgress) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TaskProgress) GetCompleted() bool {
	if m != nil {
		return m.Completed
	}
	return false
}

type Programmer struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Programmer) Reset()         { *m = Programmer{} }
func (m *Programmer) String() string { return proto.CompactTextString(m) }
func (*Programmer) ProtoMessage()    {}
func (*Programmer) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b273be58978a133, []int{3}
}

func (m *Programmer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Programmer.Unmarshal(m, b)
}
func (m *Programmer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Programmer.Marshal(b, m, deterministic)
}
func (m *Programmer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Programmer.Merge(m, src)
}
func (m *Programmer) XXX_Size() int {
	return xxx_messageInfo_Programmer.Size(m)
}
func (m *Programmer) XXX_DiscardUnknown() {
	xxx_messageInfo_Programmer.DiscardUnknown(m)
}

var xxx_messageInfo_Programmer proto.InternalMessageInfo

func (m *Programmer) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *Programmer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Programmer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Instance)(nil), "cc.arduino.cli.commands.Instance")
	proto.RegisterType((*DownloadProgress)(nil), "cc.arduino.cli.commands.DownloadProgress")
	proto.RegisterType((*TaskProgress)(nil), "cc.arduino.cli.commands.TaskProgress")
	proto.RegisterType((*Programmer)(nil), "cc.arduino.cli.commands.Programmer")
}

func init() {
	proto.RegisterFile("commands/common.proto", fileDescriptor_0b273be58978a133)
}

var fileDescriptor_0b273be58978a133 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0x69, 0x3b, 0xa3, 0xed, 0x45, 0x64, 0x08, 0x88, 0x61, 0x50, 0x29, 0x5d, 0x15, 0x64,
	0xda, 0x85, 0x6f, 0x20, 0x6e, 0x04, 0x17, 0x52, 0x5d, 0xcd, 0x46, 0x32, 0x49, 0xa6, 0x06, 0xf3,
	0x53, 0x92, 0x14, 0x61, 0xde, 0xc3, 0xf7, 0x95, 0xc6, 0xb6, 0xa3, 0xae, 0x72, 0xee, 0xc9, 0xe5,
	0xe3, 0x70, 0x0f, 0x5c, 0x50, 0xa3, 0x14, 0xd1, 0xcc, 0xd5, 0x83, 0x30, 0xba, 0xea, 0xac, 0xf1,
	0x06, 0x5d, 0x52, 0x5a, 0x11, 0xcb, 0x7a, 0xa1, 0x4d, 0x45, 0xa5, 0xa8, 0xa6, 0xad, 0x62, 0x0d,
	0xe9, 0xa3, 0x76, 0x9e, 0x68, 0xca, 0xd1, 0x39, 0xc4, 0x82, 0xe1, 0x28, 0x8f, 0xca, 0x65, 0x13,
	0x0b, 0x56, 0x7c, 0x45, 0xb0, 0x7a, 0x30, 0x9f, 0x5a, 0x1a, 0xc2, 0x9e, 0xad, 0x69, 0x2d, 0x77,
	0x0e, 0xad, 0x20, 0xe9, 0xad, 0x0c, 0x5b, 0x59, 0x33, 0x48, 0x84, 0x60, 0xb1, 0x17, 0x92, 0xe3,
	0x38, 0x58, 0x41, 0xa3, 0x6b, 0x00, 0x6f, 0x3c, 0x91, 0x6f, 0x4e, 0x1c, 0x38, 0x4e, 0xf2, 0xa8,
	0x4c, 0x9a, 0x2c, 0x38, 0x2f, 0xe2, 0xc0, 0xd1, 0x0d, 0x00, 0x1b, 0xc1, 0x9c, 0xe1, 0x45, 0xf8,
	0xfe, 0xe5, 0xa0, 0x2b, 0xc8, 0xa8, 0x51, 0x9d, 0xe4, 0x9e, 0x33, 0xbc, 0xcc, 0xa3, 0x32, 0x6d,
	0x8e, 0x46, 0xb1, 0x85, 0xb3, 0x57, 0xe2, 0x3e, 0xe6, 0x48, 0x08, 0x16, 0x9a, 0x28, 0x3e, 0x66,
	0x0a, 0x1a, 0x61, 0x38, 0x55, 0xdc, 0x39, 0xd2, 0x4e, 0xb9, 0xa6, 0xf1, 0x2f, 0x3b, 0xf9, 0xcf,
	0x7e, 0x02, 0x08, 0x5c, 0xa2, 0x14, 0xb7, 0x68, 0x0d, 0x69, 0x27, 0x89, 0xdf, 0x1b, 0xab, 0x46,
	0xfa, 0x3c, 0x8f, 0xd7, 0xfa, 0x81, 0xc7, 0x82, 0xcd, 0x29, 0x92, 0x63, 0x8a, 0xfb, 0xcd, 0xf6,
	0xb6, 0x15, 0xfe, 0xbd, 0xdf, 0x0d, 0x07, 0xaf, 0xc7, 0x02, 0xa6, 0x77, 0x43, 0xa5, 0xa8, 0x6d,
	0x47, 0xeb, 0xa9, 0x8c, 0xdd, 0x49, 0x28, 0xeb, 0xee, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x99, 0x76,
	0xf4, 0xe9, 0xc5, 0x01, 0x00, 0x00,
}
