// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands/lib.proto

package commands

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LibrarySearchStatus int32

const (
	// No search results were found.
	LibrarySearchStatus_failed LibrarySearchStatus = 0
	// Search results were found.
	LibrarySearchStatus_success LibrarySearchStatus = 1
)

var LibrarySearchStatus_name = map[int32]string{
	0: "failed",
	1: "success",
}

var LibrarySearchStatus_value = map[string]int32{
	"failed":  0,
	"success": 1,
}

func (x LibrarySearchStatus) String() string {
	return proto.EnumName(LibrarySearchStatus_name, int32(x))
}

func (LibrarySearchStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{0}
}

type LibraryLayout int32

const (
	// Library is in the 1.0 Arduino library format.
	LibraryLayout_flat_layout LibraryLayout = 0
	// Library is in the 1.5 Arduino library format.
	LibraryLayout_recursive_layout LibraryLayout = 1
)

var LibraryLayout_name = map[int32]string{
	0: "flat_layout",
	1: "recursive_layout",
}

var LibraryLayout_value = map[string]int32{
	"flat_layout":      0,
	"recursive_layout": 1,
}

func (x LibraryLayout) String() string {
	return proto.EnumName(LibraryLayout_name, int32(x))
}

func (LibraryLayout) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{1}
}

type LibraryLocation int32

const (
	// In the `libraries` subdirectory of the Arduino IDE installation.
	LibraryLocation_ide_builtin LibraryLocation = 0
	// In the `libraries` subdirectory of the user directory (sketchbook).
	LibraryLocation_user LibraryLocation = 1
	// In the `libraries` subdirectory of a platform.
	LibraryLocation_platform_builtin LibraryLocation = 2
	// When `LibraryLocation` is used in a context where a board is specified,
	// this indicates the library is in the `libraries` subdirectory of a
	// platform referenced by the board's platform.
	LibraryLocation_referenced_platform_builtin LibraryLocation = 3
)

var LibraryLocation_name = map[int32]string{
	0: "ide_builtin",
	1: "user",
	2: "platform_builtin",
	3: "referenced_platform_builtin",
}

var LibraryLocation_value = map[string]int32{
	"ide_builtin":                 0,
	"user":                        1,
	"platform_builtin":            2,
	"referenced_platform_builtin": 3,
}

func (x LibraryLocation) String() string {
	return proto.EnumName(LibraryLocation_name, int32(x))
}

func (LibraryLocation) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{2}
}

type LibraryDownloadReq struct {
	// Arduino Core Service instance from the `Init` response.
	Instance *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Name of the library.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The version of the library to download.
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryDownloadReq) Reset()         { *m = LibraryDownloadReq{} }
func (m *LibraryDownloadReq) String() string { return proto.CompactTextString(m) }
func (*LibraryDownloadReq) ProtoMessage()    {}
func (*LibraryDownloadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{0}
}

func (m *LibraryDownloadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDownloadReq.Unmarshal(m, b)
}
func (m *LibraryDownloadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDownloadReq.Marshal(b, m, deterministic)
}
func (m *LibraryDownloadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDownloadReq.Merge(m, src)
}
func (m *LibraryDownloadReq) XXX_Size() int {
	return xxx_messageInfo_LibraryDownloadReq.Size(m)
}
func (m *LibraryDownloadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDownloadReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDownloadReq proto.InternalMessageInfo

func (m *LibraryDownloadReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryDownloadReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryDownloadReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryDownloadResp struct {
	// Progress of the library download.
	Progress             *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *LibraryDownloadResp) Reset()         { *m = LibraryDownloadResp{} }
func (m *LibraryDownloadResp) String() string { return proto.CompactTextString(m) }
func (*LibraryDownloadResp) ProtoMessage()    {}
func (*LibraryDownloadResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{1}
}

func (m *LibraryDownloadResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDownloadResp.Unmarshal(m, b)
}
func (m *LibraryDownloadResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDownloadResp.Marshal(b, m, deterministic)
}
func (m *LibraryDownloadResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDownloadResp.Merge(m, src)
}
func (m *LibraryDownloadResp) XXX_Size() int {
	return xxx_messageInfo_LibraryDownloadResp.Size(m)
}
func (m *LibraryDownloadResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDownloadResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDownloadResp proto.InternalMessageInfo

func (m *LibraryDownloadResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

type LibraryInstallReq struct {
	// Arduino Core Service instance from the `Init` response.
	Instance *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Name of the library.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The version of the library to install.
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryInstallReq) Reset()         { *m = LibraryInstallReq{} }
func (m *LibraryInstallReq) String() string { return proto.CompactTextString(m) }
func (*LibraryInstallReq) ProtoMessage()    {}
func (*LibraryInstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{2}
}

func (m *LibraryInstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryInstallReq.Unmarshal(m, b)
}
func (m *LibraryInstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryInstallReq.Marshal(b, m, deterministic)
}
func (m *LibraryInstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryInstallReq.Merge(m, src)
}
func (m *LibraryInstallReq) XXX_Size() int {
	return xxx_messageInfo_LibraryInstallReq.Size(m)
}
func (m *LibraryInstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryInstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryInstallReq proto.InternalMessageInfo

func (m *LibraryInstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryInstallReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryInstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryInstallResp struct {
	// Progress of the library download.
	Progress *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	// Description of the current stage of the installation.
	TaskProgress         *TaskProgress `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LibraryInstallResp) Reset()         { *m = LibraryInstallResp{} }
func (m *LibraryInstallResp) String() string { return proto.CompactTextString(m) }
func (*LibraryInstallResp) ProtoMessage()    {}
func (*LibraryInstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{3}
}

func (m *LibraryInstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryInstallResp.Unmarshal(m, b)
}
func (m *LibraryInstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryInstallResp.Marshal(b, m, deterministic)
}
func (m *LibraryInstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryInstallResp.Merge(m, src)
}
func (m *LibraryInstallResp) XXX_Size() int {
	return xxx_messageInfo_LibraryInstallResp.Size(m)
}
func (m *LibraryInstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryInstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryInstallResp proto.InternalMessageInfo

func (m *LibraryInstallResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *LibraryInstallResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type LibraryUninstallReq struct {
	// Arduino Core Service instance from the `Init` response.
	Instance *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Name of the library.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The version of the library to uninstall.
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryUninstallReq) Reset()         { *m = LibraryUninstallReq{} }
func (m *LibraryUninstallReq) String() string { return proto.CompactTextString(m) }
func (*LibraryUninstallReq) ProtoMessage()    {}
func (*LibraryUninstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{4}
}

func (m *LibraryUninstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUninstallReq.Unmarshal(m, b)
}
func (m *LibraryUninstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUninstallReq.Marshal(b, m, deterministic)
}
func (m *LibraryUninstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUninstallReq.Merge(m, src)
}
func (m *LibraryUninstallReq) XXX_Size() int {
	return xxx_messageInfo_LibraryUninstallReq.Size(m)
}
func (m *LibraryUninstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUninstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUninstallReq proto.InternalMessageInfo

func (m *LibraryUninstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryUninstallReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryUninstallReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryUninstallResp struct {
	// Description of the current stage of the uninstallation.
	TaskProgress         *TaskProgress `protobuf:"bytes,1,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LibraryUninstallResp) Reset()         { *m = LibraryUninstallResp{} }
func (m *LibraryUninstallResp) String() string { return proto.CompactTextString(m) }
func (*LibraryUninstallResp) ProtoMessage()    {}
func (*LibraryUninstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{5}
}

func (m *LibraryUninstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUninstallResp.Unmarshal(m, b)
}
func (m *LibraryUninstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUninstallResp.Marshal(b, m, deterministic)
}
func (m *LibraryUninstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUninstallResp.Merge(m, src)
}
func (m *LibraryUninstallResp) XXX_Size() int {
	return xxx_messageInfo_LibraryUninstallResp.Size(m)
}
func (m *LibraryUninstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUninstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUninstallResp proto.InternalMessageInfo

func (m *LibraryUninstallResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type LibraryUpgradeAllReq struct {
	// Arduino Core Service instance from the `Init` response.
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LibraryUpgradeAllReq) Reset()         { *m = LibraryUpgradeAllReq{} }
func (m *LibraryUpgradeAllReq) String() string { return proto.CompactTextString(m) }
func (*LibraryUpgradeAllReq) ProtoMessage()    {}
func (*LibraryUpgradeAllReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{6}
}

func (m *LibraryUpgradeAllReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUpgradeAllReq.Unmarshal(m, b)
}
func (m *LibraryUpgradeAllReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUpgradeAllReq.Marshal(b, m, deterministic)
}
func (m *LibraryUpgradeAllReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUpgradeAllReq.Merge(m, src)
}
func (m *LibraryUpgradeAllReq) XXX_Size() int {
	return xxx_messageInfo_LibraryUpgradeAllReq.Size(m)
}
func (m *LibraryUpgradeAllReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUpgradeAllReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUpgradeAllReq proto.InternalMessageInfo

func (m *LibraryUpgradeAllReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

type LibraryUpgradeAllResp struct {
	// Progress of the downloads of files needed for the upgrades.
	Progress *DownloadProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	// Description of the current stage of the upgrade.
	TaskProgress         *TaskProgress `protobuf:"bytes,2,opt,name=task_progress,json=taskProgress,proto3" json:"task_progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *LibraryUpgradeAllResp) Reset()         { *m = LibraryUpgradeAllResp{} }
func (m *LibraryUpgradeAllResp) String() string { return proto.CompactTextString(m) }
func (*LibraryUpgradeAllResp) ProtoMessage()    {}
func (*LibraryUpgradeAllResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{7}
}

func (m *LibraryUpgradeAllResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryUpgradeAllResp.Unmarshal(m, b)
}
func (m *LibraryUpgradeAllResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryUpgradeAllResp.Marshal(b, m, deterministic)
}
func (m *LibraryUpgradeAllResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryUpgradeAllResp.Merge(m, src)
}
func (m *LibraryUpgradeAllResp) XXX_Size() int {
	return xxx_messageInfo_LibraryUpgradeAllResp.Size(m)
}
func (m *LibraryUpgradeAllResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryUpgradeAllResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryUpgradeAllResp proto.InternalMessageInfo

func (m *LibraryUpgradeAllResp) GetProgress() *DownloadProgress {
	if m != nil {
		return m.Progress
	}
	return nil
}

func (m *LibraryUpgradeAllResp) GetTaskProgress() *TaskProgress {
	if m != nil {
		return m.TaskProgress
	}
	return nil
}

type LibraryResolveDependenciesReq struct {
	// Arduino Core Service instance from the `Init` response.
	Instance *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Name of the library.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The version of the library to check dependencies of. If no version is
	// specified, dependencies of the newest version will be listed.
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryResolveDependenciesReq) Reset()         { *m = LibraryResolveDependenciesReq{} }
func (m *LibraryResolveDependenciesReq) String() string { return proto.CompactTextString(m) }
func (*LibraryResolveDependenciesReq) ProtoMessage()    {}
func (*LibraryResolveDependenciesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{8}
}

func (m *LibraryResolveDependenciesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryResolveDependenciesReq.Unmarshal(m, b)
}
func (m *LibraryResolveDependenciesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryResolveDependenciesReq.Marshal(b, m, deterministic)
}
func (m *LibraryResolveDependenciesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryResolveDependenciesReq.Merge(m, src)
}
func (m *LibraryResolveDependenciesReq) XXX_Size() int {
	return xxx_messageInfo_LibraryResolveDependenciesReq.Size(m)
}
func (m *LibraryResolveDependenciesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryResolveDependenciesReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryResolveDependenciesReq proto.InternalMessageInfo

func (m *LibraryResolveDependenciesReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryResolveDependenciesReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryResolveDependenciesReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LibraryResolveDependenciesResp struct {
	// Dependencies of the library.
	Dependencies         []*LibraryDependencyStatus `protobuf:"bytes,1,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *LibraryResolveDependenciesResp) Reset()         { *m = LibraryResolveDependenciesResp{} }
func (m *LibraryResolveDependenciesResp) String() string { return proto.CompactTextString(m) }
func (*LibraryResolveDependenciesResp) ProtoMessage()    {}
func (*LibraryResolveDependenciesResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{9}
}

func (m *LibraryResolveDependenciesResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryResolveDependenciesResp.Unmarshal(m, b)
}
func (m *LibraryResolveDependenciesResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryResolveDependenciesResp.Marshal(b, m, deterministic)
}
func (m *LibraryResolveDependenciesResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryResolveDependenciesResp.Merge(m, src)
}
func (m *LibraryResolveDependenciesResp) XXX_Size() int {
	return xxx_messageInfo_LibraryResolveDependenciesResp.Size(m)
}
func (m *LibraryResolveDependenciesResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryResolveDependenciesResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryResolveDependenciesResp proto.InternalMessageInfo

func (m *LibraryResolveDependenciesResp) GetDependencies() []*LibraryDependencyStatus {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type LibraryDependencyStatus struct {
	// The name of the library dependency.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The required version of the library dependency.
	VersionRequired string `protobuf:"bytes,2,opt,name=versionRequired,proto3" json:"versionRequired,omitempty"`
	// Version of the library dependency currently installed.
	VersionInstalled     string   `protobuf:"bytes,3,opt,name=versionInstalled,proto3" json:"versionInstalled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryDependencyStatus) Reset()         { *m = LibraryDependencyStatus{} }
func (m *LibraryDependencyStatus) String() string { return proto.CompactTextString(m) }
func (*LibraryDependencyStatus) ProtoMessage()    {}
func (*LibraryDependencyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{10}
}

func (m *LibraryDependencyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDependencyStatus.Unmarshal(m, b)
}
func (m *LibraryDependencyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDependencyStatus.Marshal(b, m, deterministic)
}
func (m *LibraryDependencyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDependencyStatus.Merge(m, src)
}
func (m *LibraryDependencyStatus) XXX_Size() int {
	return xxx_messageInfo_LibraryDependencyStatus.Size(m)
}
func (m *LibraryDependencyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDependencyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDependencyStatus proto.InternalMessageInfo

func (m *LibraryDependencyStatus) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryDependencyStatus) GetVersionRequired() string {
	if m != nil {
		return m.VersionRequired
	}
	return ""
}

func (m *LibraryDependencyStatus) GetVersionInstalled() string {
	if m != nil {
		return m.VersionInstalled
	}
	return ""
}

type LibrarySearchReq struct {
	// Arduino Core Service instance from the `Init` response.
	Instance *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// The search query.
	Query                string   `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibrarySearchReq) Reset()         { *m = LibrarySearchReq{} }
func (m *LibrarySearchReq) String() string { return proto.CompactTextString(m) }
func (*LibrarySearchReq) ProtoMessage()    {}
func (*LibrarySearchReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{11}
}

func (m *LibrarySearchReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibrarySearchReq.Unmarshal(m, b)
}
func (m *LibrarySearchReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibrarySearchReq.Marshal(b, m, deterministic)
}
func (m *LibrarySearchReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibrarySearchReq.Merge(m, src)
}
func (m *LibrarySearchReq) XXX_Size() int {
	return xxx_messageInfo_LibrarySearchReq.Size(m)
}
func (m *LibrarySearchReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibrarySearchReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibrarySearchReq proto.InternalMessageInfo

func (m *LibrarySearchReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibrarySearchReq) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type LibrarySearchResp struct {
	// The results of the search.
	Libraries []*SearchedLibrary `protobuf:"bytes,1,rep,name=libraries,proto3" json:"libraries,omitempty"`
	// Whether the search yielded results.
	Status               LibrarySearchStatus `protobuf:"varint,2,opt,name=status,proto3,enum=cc.arduino.cli.commands.LibrarySearchStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LibrarySearchResp) Reset()         { *m = LibrarySearchResp{} }
func (m *LibrarySearchResp) String() string { return proto.CompactTextString(m) }
func (*LibrarySearchResp) ProtoMessage()    {}
func (*LibrarySearchResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{12}
}

func (m *LibrarySearchResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibrarySearchResp.Unmarshal(m, b)
}
func (m *LibrarySearchResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibrarySearchResp.Marshal(b, m, deterministic)
}
func (m *LibrarySearchResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibrarySearchResp.Merge(m, src)
}
func (m *LibrarySearchResp) XXX_Size() int {
	return xxx_messageInfo_LibrarySearchResp.Size(m)
}
func (m *LibrarySearchResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibrarySearchResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibrarySearchResp proto.InternalMessageInfo

func (m *LibrarySearchResp) GetLibraries() []*SearchedLibrary {
	if m != nil {
		return m.Libraries
	}
	return nil
}

func (m *LibrarySearchResp) GetStatus() LibrarySearchStatus {
	if m != nil {
		return m.Status
	}
	return LibrarySearchStatus_failed
}

type SearchedLibrary struct {
	// Library name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The index data for the available versions of the library. The key of the
	// map is the library version.
	Releases map[string]*LibraryRelease `protobuf:"bytes,2,rep,name=releases,proto3" json:"releases,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The index data for the latest version of the library.
	Latest               *LibraryRelease `protobuf:"bytes,3,opt,name=latest,proto3" json:"latest,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SearchedLibrary) Reset()         { *m = SearchedLibrary{} }
func (m *SearchedLibrary) String() string { return proto.CompactTextString(m) }
func (*SearchedLibrary) ProtoMessage()    {}
func (*SearchedLibrary) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{13}
}

func (m *SearchedLibrary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchedLibrary.Unmarshal(m, b)
}
func (m *SearchedLibrary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchedLibrary.Marshal(b, m, deterministic)
}
func (m *SearchedLibrary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchedLibrary.Merge(m, src)
}
func (m *SearchedLibrary) XXX_Size() int {
	return xxx_messageInfo_SearchedLibrary.Size(m)
}
func (m *SearchedLibrary) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchedLibrary.DiscardUnknown(m)
}

var xxx_messageInfo_SearchedLibrary proto.InternalMessageInfo

func (m *SearchedLibrary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchedLibrary) GetReleases() map[string]*LibraryRelease {
	if m != nil {
		return m.Releases
	}
	return nil
}

func (m *SearchedLibrary) GetLatest() *LibraryRelease {
	if m != nil {
		return m.Latest
	}
	return nil
}

type LibraryRelease struct {
	// Value of the `author` field in library.properties.
	Author string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	// Value of the `version` field in library.properties.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Value of the `maintainer` field in library.properties.
	Maintainer string `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	// Value of the `sentence` field in library.properties.
	Sentence string `protobuf:"bytes,4,opt,name=sentence,proto3" json:"sentence,omitempty"`
	// Value of the `paragraph` field in library.properties.
	Paragraph string `protobuf:"bytes,5,opt,name=paragraph,proto3" json:"paragraph,omitempty"`
	// Value of the `url` field in library.properties.
	Website string `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	// Value of the `category` field in library.properties.
	Category string `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	// Value of the `architectures` field in library.properties.
	Architectures []string `protobuf:"bytes,8,rep,name=architectures,proto3" json:"architectures,omitempty"`
	// The type categories of the library, as defined in the libraries index.
	// Possible values: `Arduino`, `Partner`, `Recommended`, `Contributed`,
	// `Retired`.
	Types []string `protobuf:"bytes,9,rep,name=types,proto3" json:"types,omitempty"`
	// Information about the library archive file.
	Resources *DownloadResource `protobuf:"bytes,10,opt,name=resources,proto3" json:"resources,omitempty"`
	// Value of the `license` field in library.properties.
	License string `protobuf:"bytes,11,opt,name=license,proto3" json:"license,omitempty"`
	// Value of the `includes` field in library.properties.
	ProvidesIncludes []string `protobuf:"bytes,12,rep,name=provides_includes,json=providesIncludes,proto3" json:"provides_includes,omitempty"`
	// The names of the library's dependencies, as defined by the 'depends'
	// field of library.properties.
	Dependencies         []*LibraryDependency `protobuf:"bytes,13,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *LibraryRelease) Reset()         { *m = LibraryRelease{} }
func (m *LibraryRelease) String() string { return proto.CompactTextString(m) }
func (*LibraryRelease) ProtoMessage()    {}
func (*LibraryRelease) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{14}
}

func (m *LibraryRelease) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryRelease.Unmarshal(m, b)
}
func (m *LibraryRelease) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryRelease.Marshal(b, m, deterministic)
}
func (m *LibraryRelease) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryRelease.Merge(m, src)
}
func (m *LibraryRelease) XXX_Size() int {
	return xxx_messageInfo_LibraryRelease.Size(m)
}
func (m *LibraryRelease) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryRelease.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryRelease proto.InternalMessageInfo

func (m *LibraryRelease) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *LibraryRelease) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LibraryRelease) GetMaintainer() string {
	if m != nil {
		return m.Maintainer
	}
	return ""
}

func (m *LibraryRelease) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

func (m *LibraryRelease) GetParagraph() string {
	if m != nil {
		return m.Paragraph
	}
	return ""
}

func (m *LibraryRelease) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *LibraryRelease) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *LibraryRelease) GetArchitectures() []string {
	if m != nil {
		return m.Architectures
	}
	return nil
}

func (m *LibraryRelease) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *LibraryRelease) GetResources() *DownloadResource {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *LibraryRelease) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

func (m *LibraryRelease) GetProvidesIncludes() []string {
	if m != nil {
		return m.ProvidesIncludes
	}
	return nil
}

func (m *LibraryRelease) GetDependencies() []*LibraryDependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type LibraryDependency struct {
	// Library name of the dependency.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version constraint of the dependency.
	VersionConstraint    string   `protobuf:"bytes,2,opt,name=version_constraint,json=versionConstraint,proto3" json:"version_constraint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryDependency) Reset()         { *m = LibraryDependency{} }
func (m *LibraryDependency) String() string { return proto.CompactTextString(m) }
func (*LibraryDependency) ProtoMessage()    {}
func (*LibraryDependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{15}
}

func (m *LibraryDependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryDependency.Unmarshal(m, b)
}
func (m *LibraryDependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryDependency.Marshal(b, m, deterministic)
}
func (m *LibraryDependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryDependency.Merge(m, src)
}
func (m *LibraryDependency) XXX_Size() int {
	return xxx_messageInfo_LibraryDependency.Size(m)
}
func (m *LibraryDependency) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryDependency.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryDependency proto.InternalMessageInfo

func (m *LibraryDependency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryDependency) GetVersionConstraint() string {
	if m != nil {
		return m.VersionConstraint
	}
	return ""
}

type DownloadResource struct {
	// Download URL of the library archive.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Filename of the library archive.
	Archivefilename string `protobuf:"bytes,2,opt,name=archivefilename,proto3" json:"archivefilename,omitempty"`
	// Checksum of the library archive.
	Checksum string `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	// File size of the library archive.
	Size int64 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	// The directory under the staging subdirectory of the data directory the
	// library archive file will be downloaded to.
	Cachepath            string   `protobuf:"bytes,5,opt,name=cachepath,proto3" json:"cachepath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DownloadResource) Reset()         { *m = DownloadResource{} }
func (m *DownloadResource) String() string { return proto.CompactTextString(m) }
func (*DownloadResource) ProtoMessage()    {}
func (*DownloadResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{16}
}

func (m *DownloadResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DownloadResource.Unmarshal(m, b)
}
func (m *DownloadResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DownloadResource.Marshal(b, m, deterministic)
}
func (m *DownloadResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DownloadResource.Merge(m, src)
}
func (m *DownloadResource) XXX_Size() int {
	return xxx_messageInfo_DownloadResource.Size(m)
}
func (m *DownloadResource) XXX_DiscardUnknown() {
	xxx_messageInfo_DownloadResource.DiscardUnknown(m)
}

var xxx_messageInfo_DownloadResource proto.InternalMessageInfo

func (m *DownloadResource) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *DownloadResource) GetArchivefilename() string {
	if m != nil {
		return m.Archivefilename
	}
	return ""
}

func (m *DownloadResource) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *DownloadResource) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *DownloadResource) GetCachepath() string {
	if m != nil {
		return m.Cachepath
	}
	return ""
}

type LibraryListReq struct {
	// Arduino Core Service instance from the `Init` response.
	Instance *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	// Whether to include built-in libraries (from platforms and the Arduino
	// IDE) in the listing.
	All bool `protobuf:"varint,2,opt,name=all,proto3" json:"all,omitempty"`
	// Whether to list only libraries for which there is a newer version than
	// the installed version available in the libraries index.
	Updatable bool `protobuf:"varint,3,opt,name=updatable,proto3" json:"updatable,omitempty"`
	// If set filters out the libraries not matching name
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// By setting this field all duplicate libraries are filtered out leaving
	// only the libraries that will be used to compile for the specified board FQBN.
	Fqbn                 string   `protobuf:"bytes,5,opt,name=fqbn,proto3" json:"fqbn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryListReq) Reset()         { *m = LibraryListReq{} }
func (m *LibraryListReq) String() string { return proto.CompactTextString(m) }
func (*LibraryListReq) ProtoMessage()    {}
func (*LibraryListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{17}
}

func (m *LibraryListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryListReq.Unmarshal(m, b)
}
func (m *LibraryListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryListReq.Marshal(b, m, deterministic)
}
func (m *LibraryListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryListReq.Merge(m, src)
}
func (m *LibraryListReq) XXX_Size() int {
	return xxx_messageInfo_LibraryListReq.Size(m)
}
func (m *LibraryListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryListReq.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryListReq proto.InternalMessageInfo

func (m *LibraryListReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *LibraryListReq) GetAll() bool {
	if m != nil {
		return m.All
	}
	return false
}

func (m *LibraryListReq) GetUpdatable() bool {
	if m != nil {
		return m.Updatable
	}
	return false
}

func (m *LibraryListReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LibraryListReq) GetFqbn() string {
	if m != nil {
		return m.Fqbn
	}
	return ""
}

type LibraryListResp struct {
	// List of installed libraries.
	InstalledLibrary     []*InstalledLibrary `protobuf:"bytes,1,rep,name=installed_library,json=installedLibrary,proto3" json:"installed_library,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *LibraryListResp) Reset()         { *m = LibraryListResp{} }
func (m *LibraryListResp) String() string { return proto.CompactTextString(m) }
func (*LibraryListResp) ProtoMessage()    {}
func (*LibraryListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{18}
}

func (m *LibraryListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryListResp.Unmarshal(m, b)
}
func (m *LibraryListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryListResp.Marshal(b, m, deterministic)
}
func (m *LibraryListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryListResp.Merge(m, src)
}
func (m *LibraryListResp) XXX_Size() int {
	return xxx_messageInfo_LibraryListResp.Size(m)
}
func (m *LibraryListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryListResp.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryListResp proto.InternalMessageInfo

func (m *LibraryListResp) GetInstalledLibrary() []*InstalledLibrary {
	if m != nil {
		return m.InstalledLibrary
	}
	return nil
}

type InstalledLibrary struct {
	// Information about the library.
	Library *Library `protobuf:"bytes,1,opt,name=library,proto3" json:"library,omitempty"`
	// When the `updatable` field of the `LibraryList` request is set to `true`,
	// this will contain information on the latest version of the library in the
	// libraries index.
	Release              *LibraryRelease `protobuf:"bytes,2,opt,name=release,proto3" json:"release,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InstalledLibrary) Reset()         { *m = InstalledLibrary{} }
func (m *InstalledLibrary) String() string { return proto.CompactTextString(m) }
func (*InstalledLibrary) ProtoMessage()    {}
func (*InstalledLibrary) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{19}
}

func (m *InstalledLibrary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstalledLibrary.Unmarshal(m, b)
}
func (m *InstalledLibrary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstalledLibrary.Marshal(b, m, deterministic)
}
func (m *InstalledLibrary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstalledLibrary.Merge(m, src)
}
func (m *InstalledLibrary) XXX_Size() int {
	return xxx_messageInfo_InstalledLibrary.Size(m)
}
func (m *InstalledLibrary) XXX_DiscardUnknown() {
	xxx_messageInfo_InstalledLibrary.DiscardUnknown(m)
}

var xxx_messageInfo_InstalledLibrary proto.InternalMessageInfo

func (m *InstalledLibrary) GetLibrary() *Library {
	if m != nil {
		return m.Library
	}
	return nil
}

func (m *InstalledLibrary) GetRelease() *LibraryRelease {
	if m != nil {
		return m.Release
	}
	return nil
}

type Library struct {
	// The library's directory name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Value of the `author` field in library.properties.
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// Value of the `maintainer` field in library.properties.
	Maintainer string `protobuf:"bytes,3,opt,name=maintainer,proto3" json:"maintainer,omitempty"`
	// Value of the `sentence` field in library.properties.
	Sentence string `protobuf:"bytes,4,opt,name=sentence,proto3" json:"sentence,omitempty"`
	// Value of the `paragraph` field in library.properties.
	Paragraph string `protobuf:"bytes,5,opt,name=paragraph,proto3" json:"paragraph,omitempty"`
	// Value of the `url` field in library.properties.
	Website string `protobuf:"bytes,6,opt,name=website,proto3" json:"website,omitempty"`
	// Value of the `category` field in library.properties.
	Category string `protobuf:"bytes,7,opt,name=category,proto3" json:"category,omitempty"`
	// Value of the `architectures` field in library.properties.
	Architectures []string `protobuf:"bytes,8,rep,name=architectures,proto3" json:"architectures,omitempty"`
	// The type categories of the library. Possible values: `Arduino`,
	// `Partner`, `Recommended`, `Contributed`, `Retired`.
	Types []string `protobuf:"bytes,9,rep,name=types,proto3" json:"types,omitempty"`
	// The path of the library directory.
	InstallDir string `protobuf:"bytes,10,opt,name=install_dir,json=installDir,proto3" json:"install_dir,omitempty"`
	// The location of the library's source files.
	SourceDir string `protobuf:"bytes,11,opt,name=source_dir,json=sourceDir,proto3" json:"source_dir,omitempty"`
	// The location of the library's `utility` directory.
	UtilityDir string `protobuf:"bytes,12,opt,name=utility_dir,json=utilityDir,proto3" json:"utility_dir,omitempty"`
	// If `location` is `platform_builtin` or `referenced_platform_builtin`, the
	// identifying string for the platform containing the library
	// (e.g., `arduino:avr@1.8.2`).
	ContainerPlatform string `protobuf:"bytes,14,opt,name=container_platform,json=containerPlatform,proto3" json:"container_platform,omitempty"`
	// Value of the `name` field in library.properties.
	RealName string `protobuf:"bytes,16,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	// Value of the `dot_a_linkage` field in library.properties.
	DotALinkage bool `protobuf:"varint,17,opt,name=dot_a_linkage,json=dotALinkage,proto3" json:"dot_a_linkage,omitempty"`
	// Value of the `precompiled` field in library.properties.
	Precompiled bool `protobuf:"varint,18,opt,name=precompiled,proto3" json:"precompiled,omitempty"`
	// Value of the `ldflags` field in library.properties.
	LdFlags string `protobuf:"bytes,19,opt,name=ld_flags,json=ldFlags,proto3" json:"ld_flags,omitempty"`
	// A library.properties file is not present in the library's root directory.
	IsLegacy bool `protobuf:"varint,20,opt,name=is_legacy,json=isLegacy,proto3" json:"is_legacy,omitempty"`
	// Value of the `version` field in library.properties.
	Version string `protobuf:"bytes,21,opt,name=version,proto3" json:"version,omitempty"`
	// Value of the `license` field in library.properties.
	License string `protobuf:"bytes,22,opt,name=license,proto3" json:"license,omitempty"`
	// The data from the library's library.properties file, including unused
	// fields.
	Properties map[string]string `protobuf:"bytes,23,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The location type of the library installation.
	Location LibraryLocation `protobuf:"varint,24,opt,name=location,proto3,enum=cc.arduino.cli.commands.LibraryLocation" json:"location,omitempty"`
	// The library format type.
	Layout LibraryLayout `protobuf:"varint,25,opt,name=layout,proto3,enum=cc.arduino.cli.commands.LibraryLayout" json:"layout,omitempty"`
	// The example sketches provided by the library
	Examples []string `protobuf:"bytes,26,rep,name=examples,proto3" json:"examples,omitempty"`
	// Value of the `includes` field in library.properties or, if missing, the list of
	// include files available on the library source root directory.
	ProvidesIncludes []string `protobuf:"bytes,27,rep,name=provides_includes,json=providesIncludes,proto3" json:"provides_includes,omitempty"`
	// Map of FQBNs that specifies if library is compatible with this library
	CompatibleWith       map[string]bool `protobuf:"bytes,28,rep,name=compatible_with,json=compatibleWith,proto3" json:"compatible_with,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Library) Reset()         { *m = Library{} }
func (m *Library) String() string { return proto.CompactTextString(m) }
func (*Library) ProtoMessage()    {}
func (*Library) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{20}
}

func (m *Library) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Library.Unmarshal(m, b)
}
func (m *Library) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Library.Marshal(b, m, deterministic)
}
func (m *Library) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Library.Merge(m, src)
}
func (m *Library) XXX_Size() int {
	return xxx_messageInfo_Library.Size(m)
}
func (m *Library) XXX_DiscardUnknown() {
	xxx_messageInfo_Library.DiscardUnknown(m)
}

var xxx_messageInfo_Library proto.InternalMessageInfo

func (m *Library) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Library) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Library) GetMaintainer() string {
	if m != nil {
		return m.Maintainer
	}
	return ""
}

func (m *Library) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

func (m *Library) GetParagraph() string {
	if m != nil {
		return m.Paragraph
	}
	return ""
}

func (m *Library) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Library) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *Library) GetArchitectures() []string {
	if m != nil {
		return m.Architectures
	}
	return nil
}

func (m *Library) GetTypes() []string {
	if m != nil {
		return m.Types
	}
	return nil
}

func (m *Library) GetInstallDir() string {
	if m != nil {
		return m.InstallDir
	}
	return ""
}

func (m *Library) GetSourceDir() string {
	if m != nil {
		return m.SourceDir
	}
	return ""
}

func (m *Library) GetUtilityDir() string {
	if m != nil {
		return m.UtilityDir
	}
	return ""
}

func (m *Library) GetContainerPlatform() string {
	if m != nil {
		return m.ContainerPlatform
	}
	return ""
}

func (m *Library) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *Library) GetDotALinkage() bool {
	if m != nil {
		return m.DotALinkage
	}
	return false
}

func (m *Library) GetPrecompiled() bool {
	if m != nil {
		return m.Precompiled
	}
	return false
}

func (m *Library) GetLdFlags() string {
	if m != nil {
		return m.LdFlags
	}
	return ""
}

func (m *Library) GetIsLegacy() bool {
	if m != nil {
		return m.IsLegacy
	}
	return false
}

func (m *Library) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Library) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

func (m *Library) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Library) GetLocation() LibraryLocation {
	if m != nil {
		return m.Location
	}
	return LibraryLocation_ide_builtin
}

func (m *Library) GetLayout() LibraryLayout {
	if m != nil {
		return m.Layout
	}
	return LibraryLayout_flat_layout
}

func (m *Library) GetExamples() []string {
	if m != nil {
		return m.Examples
	}
	return nil
}

func (m *Library) GetProvidesIncludes() []string {
	if m != nil {
		return m.ProvidesIncludes
	}
	return nil
}

func (m *Library) GetCompatibleWith() map[string]bool {
	if m != nil {
		return m.CompatibleWith
	}
	return nil
}

type ZipLibraryInstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Path                 string    `protobuf:"bytes,2,opt,name=Path,json=path,proto3" json:"Path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ZipLibraryInstallReq) Reset()         { *m = ZipLibraryInstallReq{} }
func (m *ZipLibraryInstallReq) String() string { return proto.CompactTextString(m) }
func (*ZipLibraryInstallReq) ProtoMessage()    {}
func (*ZipLibraryInstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{21}
}

func (m *ZipLibraryInstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZipLibraryInstallReq.Unmarshal(m, b)
}
func (m *ZipLibraryInstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZipLibraryInstallReq.Marshal(b, m, deterministic)
}
func (m *ZipLibraryInstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZipLibraryInstallReq.Merge(m, src)
}
func (m *ZipLibraryInstallReq) XXX_Size() int {
	return xxx_messageInfo_ZipLibraryInstallReq.Size(m)
}
func (m *ZipLibraryInstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ZipLibraryInstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_ZipLibraryInstallReq proto.InternalMessageInfo

func (m *ZipLibraryInstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *ZipLibraryInstallReq) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type ZipLibraryInstallResp struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZipLibraryInstallResp) Reset()         { *m = ZipLibraryInstallResp{} }
func (m *ZipLibraryInstallResp) String() string { return proto.CompactTextString(m) }
func (*ZipLibraryInstallResp) ProtoMessage()    {}
func (*ZipLibraryInstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{22}
}

func (m *ZipLibraryInstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZipLibraryInstallResp.Unmarshal(m, b)
}
func (m *ZipLibraryInstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZipLibraryInstallResp.Marshal(b, m, deterministic)
}
func (m *ZipLibraryInstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZipLibraryInstallResp.Merge(m, src)
}
func (m *ZipLibraryInstallResp) XXX_Size() int {
	return xxx_messageInfo_ZipLibraryInstallResp.Size(m)
}
func (m *ZipLibraryInstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ZipLibraryInstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_ZipLibraryInstallResp proto.InternalMessageInfo

func (m *ZipLibraryInstallResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GitLibraryInstallReq struct {
	Instance             *Instance `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string    `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GitLibraryInstallReq) Reset()         { *m = GitLibraryInstallReq{} }
func (m *GitLibraryInstallReq) String() string { return proto.CompactTextString(m) }
func (*GitLibraryInstallReq) ProtoMessage()    {}
func (*GitLibraryInstallReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{23}
}

func (m *GitLibraryInstallReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitLibraryInstallReq.Unmarshal(m, b)
}
func (m *GitLibraryInstallReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitLibraryInstallReq.Marshal(b, m, deterministic)
}
func (m *GitLibraryInstallReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitLibraryInstallReq.Merge(m, src)
}
func (m *GitLibraryInstallReq) XXX_Size() int {
	return xxx_messageInfo_GitLibraryInstallReq.Size(m)
}
func (m *GitLibraryInstallReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GitLibraryInstallReq.DiscardUnknown(m)
}

var xxx_messageInfo_GitLibraryInstallReq proto.InternalMessageInfo

func (m *GitLibraryInstallReq) GetInstance() *Instance {
	if m != nil {
		return m.Instance
	}
	return nil
}

func (m *GitLibraryInstallReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GitLibraryInstallReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GitLibraryInstallResp struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GitLibraryInstallResp) Reset()         { *m = GitLibraryInstallResp{} }
func (m *GitLibraryInstallResp) String() string { return proto.CompactTextString(m) }
func (*GitLibraryInstallResp) ProtoMessage()    {}
func (*GitLibraryInstallResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_9feed0d29806df6c, []int{24}
}

func (m *GitLibraryInstallResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GitLibraryInstallResp.Unmarshal(m, b)
}
func (m *GitLibraryInstallResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GitLibraryInstallResp.Marshal(b, m, deterministic)
}
func (m *GitLibraryInstallResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GitLibraryInstallResp.Merge(m, src)
}
func (m *GitLibraryInstallResp) XXX_Size() int {
	return xxx_messageInfo_GitLibraryInstallResp.Size(m)
}
func (m *GitLibraryInstallResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GitLibraryInstallResp.DiscardUnknown(m)
}

var xxx_messageInfo_GitLibraryInstallResp proto.InternalMessageInfo

func (m *GitLibraryInstallResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterEnum("cc.arduino.cli.commands.LibrarySearchStatus", LibrarySearchStatus_name, LibrarySearchStatus_value)
	proto.RegisterEnum("cc.arduino.cli.commands.LibraryLayout", LibraryLayout_name, LibraryLayout_value)
	proto.RegisterEnum("cc.arduino.cli.commands.LibraryLocation", LibraryLocation_name, LibraryLocation_value)
	proto.RegisterType((*LibraryDownloadReq)(nil), "cc.arduino.cli.commands.LibraryDownloadReq")
	proto.RegisterType((*LibraryDownloadResp)(nil), "cc.arduino.cli.commands.LibraryDownloadResp")
	proto.RegisterType((*LibraryInstallReq)(nil), "cc.arduino.cli.commands.LibraryInstallReq")
	proto.RegisterType((*LibraryInstallResp)(nil), "cc.arduino.cli.commands.LibraryInstallResp")
	proto.RegisterType((*LibraryUninstallReq)(nil), "cc.arduino.cli.commands.LibraryUninstallReq")
	proto.RegisterType((*LibraryUninstallResp)(nil), "cc.arduino.cli.commands.LibraryUninstallResp")
	proto.RegisterType((*LibraryUpgradeAllReq)(nil), "cc.arduino.cli.commands.LibraryUpgradeAllReq")
	proto.RegisterType((*LibraryUpgradeAllResp)(nil), "cc.arduino.cli.commands.LibraryUpgradeAllResp")
	proto.RegisterType((*LibraryResolveDependenciesReq)(nil), "cc.arduino.cli.commands.LibraryResolveDependenciesReq")
	proto.RegisterType((*LibraryResolveDependenciesResp)(nil), "cc.arduino.cli.commands.LibraryResolveDependenciesResp")
	proto.RegisterType((*LibraryDependencyStatus)(nil), "cc.arduino.cli.commands.LibraryDependencyStatus")
	proto.RegisterType((*LibrarySearchReq)(nil), "cc.arduino.cli.commands.LibrarySearchReq")
	proto.RegisterType((*LibrarySearchResp)(nil), "cc.arduino.cli.commands.LibrarySearchResp")
	proto.RegisterType((*SearchedLibrary)(nil), "cc.arduino.cli.commands.SearchedLibrary")
	proto.RegisterMapType((map[string]*LibraryRelease)(nil), "cc.arduino.cli.commands.SearchedLibrary.ReleasesEntry")
	proto.RegisterType((*LibraryRelease)(nil), "cc.arduino.cli.commands.LibraryRelease")
	proto.RegisterType((*LibraryDependency)(nil), "cc.arduino.cli.commands.LibraryDependency")
	proto.RegisterType((*DownloadResource)(nil), "cc.arduino.cli.commands.DownloadResource")
	proto.RegisterType((*LibraryListReq)(nil), "cc.arduino.cli.commands.LibraryListReq")
	proto.RegisterType((*LibraryListResp)(nil), "cc.arduino.cli.commands.LibraryListResp")
	proto.RegisterType((*InstalledLibrary)(nil), "cc.arduino.cli.commands.InstalledLibrary")
	proto.RegisterType((*Library)(nil), "cc.arduino.cli.commands.Library")
	proto.RegisterMapType((map[string]bool)(nil), "cc.arduino.cli.commands.Library.CompatibleWithEntry")
	proto.RegisterMapType((map[string]string)(nil), "cc.arduino.cli.commands.Library.PropertiesEntry")
	proto.RegisterType((*ZipLibraryInstallReq)(nil), "cc.arduino.cli.commands.ZipLibraryInstallReq")
	proto.RegisterType((*ZipLibraryInstallResp)(nil), "cc.arduino.cli.commands.ZipLibraryInstallResp")
	proto.RegisterType((*GitLibraryInstallReq)(nil), "cc.arduino.cli.commands.GitLibraryInstallReq")
	proto.RegisterType((*GitLibraryInstallResp)(nil), "cc.arduino.cli.commands.GitLibraryInstallResp")
}

func init() {
	proto.RegisterFile("commands/lib.proto", fileDescriptor_9feed0d29806df6c)
}

var fileDescriptor_9feed0d29806df6c = []byte{
	// 1459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xdd, 0x6f, 0x1b, 0x45,
	0x10, 0xef, 0xc5, 0x69, 0x62, 0x8f, 0xf3, 0x71, 0xd9, 0x26, 0xed, 0x35, 0xfd, 0x0a, 0x27, 0x3e,
	0xd2, 0x94, 0x38, 0x28, 0xa0, 0x0a, 0x55, 0x2a, 0x28, 0x34, 0x6d, 0x55, 0x14, 0x55, 0xd1, 0xf5,
	0x03, 0xa9, 0x02, 0x9d, 0xd6, 0x77, 0x6b, 0x7b, 0x95, 0xf5, 0xdd, 0x65, 0x77, 0xcf, 0xc5, 0xf0,
	0xc2, 0xc7, 0x2b, 0x2f, 0xbc, 0xf3, 0x00, 0x4f, 0x48, 0xfc, 0x59, 0xfc, 0x01, 0xfc, 0x0d, 0x68,
	0xf7, 0xf6, 0xce, 0x67, 0xc7, 0xae, 0x03, 0x0a, 0x05, 0xf1, 0x94, 0xdb, 0x99, 0x9d, 0x99, 0xdf,
	0xce, 0xcc, 0xfe, 0x76, 0x1c, 0x40, 0x41, 0xdc, 0xed, 0xe2, 0x28, 0x14, 0x3b, 0x8c, 0x36, 0x1b,
	0x09, 0x8f, 0x65, 0x8c, 0x2e, 0x05, 0x41, 0x03, 0xf3, 0x30, 0xa5, 0x51, 0xdc, 0x08, 0x18, 0x6d,
	0xe4, 0x5b, 0xd6, 0xd7, 0x8a, 0xcd, 0xea, 0x23, 0x8e, 0xb2, 0xfd, 0xee, 0xb7, 0x16, 0xa0, 0x03,
	0xda, 0xe4, 0x98, 0xf7, 0xf7, 0xe3, 0x97, 0x11, 0x8b, 0x71, 0xe8, 0x91, 0x63, 0x74, 0x17, 0xaa,
	0x34, 0x12, 0x12, 0x47, 0x01, 0x71, 0xac, 0x0d, 0x6b, 0xb3, 0xbe, 0xfb, 0x46, 0x63, 0x82, 0xe7,
	0xc6, 0x23, 0xb3, 0xd1, 0x2b, 0x4c, 0x10, 0x82, 0xd9, 0x08, 0x77, 0x89, 0x33, 0xb3, 0x61, 0x6d,
	0xd6, 0x3c, 0xfd, 0x8d, 0x1c, 0x98, 0xef, 0x11, 0x2e, 0x68, 0x1c, 0x39, 0x15, 0x2d, 0xce, 0x97,
	0xee, 0xe7, 0x70, 0xe1, 0x04, 0x04, 0x91, 0xa0, 0xfb, 0x50, 0x4d, 0x78, 0xdc, 0xe6, 0x44, 0x08,
	0x83, 0xe1, 0xe6, 0x44, 0x0c, 0xb9, 0xe1, 0xa1, 0x31, 0xf0, 0x0a, 0x53, 0xf7, 0x1b, 0x0b, 0x56,
	0x8c, 0x7b, 0x8d, 0x94, 0xb1, 0xd7, 0x7e, 0xc0, 0x5f, 0x07, 0x49, 0x2e, 0x20, 0x9c, 0xd9, 0x01,
	0xd1, 0xa7, 0xb0, 0x28, 0xb1, 0x38, 0xf2, 0x0b, 0x5f, 0x33, 0xda, 0xd7, 0x5b, 0x13, 0x7d, 0x3d,
	0xc5, 0xe2, 0xa8, 0xf0, 0xb3, 0x20, 0x4b, 0x2b, 0xf7, 0x3b, 0xab, 0xa8, 0xc5, 0xb3, 0x88, 0xfe,
	0x4b, 0xe9, 0x6a, 0xc2, 0xea, 0x49, 0x0c, 0x22, 0x39, 0x79, 0x50, 0xeb, 0xef, 0x1f, 0xf4, 0xd9,
	0x20, 0x46, 0xd2, 0xe6, 0x38, 0x24, 0x7b, 0x67, 0x71, 0x50, 0xf7, 0x37, 0x0b, 0xd6, 0xc6, 0xf8,
	0xfd, 0x6f, 0x16, 0xfb, 0x07, 0x0b, 0xae, 0x19, 0xb0, 0x1e, 0x11, 0x31, 0xeb, 0x91, 0x7d, 0x92,
	0x90, 0x28, 0x24, 0x51, 0x40, 0x89, 0x78, 0xed, 0x65, 0xef, 0xc1, 0xf5, 0x57, 0xa1, 0x11, 0x09,
	0x7a, 0x0a, 0x0b, 0x61, 0x49, 0xe6, 0x58, 0x1b, 0x95, 0xcd, 0xfa, 0xee, 0x7b, 0x13, 0x21, 0xe5,
	0xac, 0x92, 0xdb, 0xf4, 0x9f, 0x48, 0x2c, 0x53, 0xe1, 0x0d, 0x79, 0x71, 0xbf, 0xb7, 0xe0, 0xd2,
	0x84, 0x9d, 0xc5, 0x09, 0xac, 0xd2, 0x09, 0x36, 0x61, 0xd9, 0x40, 0xf6, 0xc8, 0x71, 0x4a, 0x39,
	0x09, 0xcd, 0x01, 0x47, 0xc5, 0x68, 0x0b, 0x6c, 0x23, 0x32, 0xd7, 0x9e, 0x84, 0xe6, 0xd0, 0x27,
	0xe4, 0x6e, 0x1b, 0x6c, 0x03, 0xe2, 0x09, 0xc1, 0x3c, 0xe8, 0x9c, 0x41, 0xfa, 0x57, 0xe1, 0xfc,
	0x71, 0x4a, 0x78, 0xdf, 0xc0, 0xcb, 0x16, 0xee, 0x2f, 0x03, 0x3e, 0xcc, 0x23, 0x89, 0x04, 0x3d,
	0x80, 0x1a, 0xd3, 0xc2, 0x41, 0x5e, 0x37, 0x27, 0xc6, 0xca, 0xec, 0x48, 0x98, 0x97, 0x6b, 0x60,
	0x8a, 0xf6, 0x61, 0x4e, 0xe8, 0xd4, 0xe9, 0xa0, 0x4b, 0xbb, 0xef, 0x4e, 0x2b, 0x4e, 0xe6, 0xcb,
	0x14, 0xc6, 0xd8, 0xba, 0x3f, 0xcf, 0xc0, 0xf2, 0x48, 0x90, 0xb1, 0xa5, 0xf0, 0xa0, 0xca, 0x09,
	0x23, 0x58, 0x10, 0x15, 0x4f, 0x81, 0xbe, 0x7d, 0x5a, 0xd0, 0x0d, 0xcf, 0x18, 0xde, 0x8f, 0x24,
	0xef, 0x7b, 0x85, 0x1f, 0xf4, 0x31, 0xcc, 0x31, 0x2c, 0x89, 0x90, 0xba, 0x54, 0xf5, 0xdd, 0x77,
	0xa6, 0x9d, 0xc0, 0x38, 0xf2, 0x8c, 0xd9, 0x7a, 0x08, 0x8b, 0x43, 0xbe, 0x91, 0x0d, 0x95, 0x23,
	0xd2, 0x37, 0xc0, 0xd5, 0x27, 0xba, 0x0b, 0xe7, 0x7b, 0x98, 0xa5, 0xc4, 0xdc, 0xde, 0x53, 0x87,
	0xc8, 0xac, 0xee, 0xcc, 0x7c, 0x68, 0xb9, 0x7f, 0x54, 0x60, 0x69, 0x58, 0x8b, 0x2e, 0xc2, 0x1c,
	0x4e, 0x65, 0x27, 0xe6, 0x26, 0x94, 0x59, 0x95, 0xaf, 0xdc, 0xcc, 0xd0, 0x95, 0x43, 0xd7, 0x01,
	0xba, 0x98, 0x46, 0x12, 0xd3, 0x88, 0x70, 0xd3, 0x9a, 0x25, 0x09, 0x5a, 0x87, 0xaa, 0x20, 0x91,
	0x24, 0xaa, 0x01, 0x67, 0xb5, 0xb6, 0x58, 0xa3, 0xab, 0x50, 0x4b, 0x30, 0xc7, 0x6d, 0x8e, 0x93,
	0x8e, 0x73, 0x5e, 0x2b, 0x07, 0x02, 0x15, 0xf3, 0x25, 0x69, 0x0a, 0x2a, 0x89, 0x33, 0x97, 0xc5,
	0x34, 0x4b, 0xe5, 0x33, 0xc0, 0x92, 0xb4, 0x63, 0xde, 0x77, 0xe6, 0x33, 0x9f, 0xf9, 0x1a, 0xbd,
	0x09, 0x8b, 0xaa, 0x48, 0x54, 0x92, 0x40, 0xa6, 0x9c, 0x08, 0xa7, 0xba, 0x51, 0xd9, 0xac, 0x79,
	0xc3, 0x42, 0xd5, 0xd7, 0xb2, 0x9f, 0x10, 0xe1, 0xd4, 0xb4, 0x36, 0x5b, 0xa0, 0x87, 0x50, 0xe3,
	0x44, 0xc4, 0x29, 0x0f, 0x88, 0x70, 0xe0, 0x94, 0x0c, 0xeb, 0x19, 0x0b, 0x6f, 0x60, 0xab, 0xa0,
	0x33, 0x1a, 0x90, 0x48, 0x10, 0xa7, 0x9e, 0x41, 0x37, 0x4b, 0x74, 0x0b, 0x56, 0x12, 0x1e, 0xf7,
	0x68, 0x48, 0x84, 0x4f, 0xa3, 0x80, 0xa5, 0x21, 0x11, 0xce, 0x82, 0x06, 0x61, 0xe7, 0x8a, 0x47,
	0x46, 0x8e, 0x1e, 0x8f, 0x90, 0xd5, 0xa2, 0xee, 0xcf, 0xad, 0xd3, 0x93, 0xd5, 0x08, 0x4d, 0x3d,
	0x2f, 0xae, 0xed, 0x60, 0xcb, 0xd8, 0x4b, 0xb1, 0x0d, 0xc8, 0xd4, 0xd7, 0x0f, 0xe2, 0x48, 0x48,
	0xae, 0xea, 0x69, 0x2a, 0xbf, 0x62, 0x34, 0xf7, 0x0a, 0x85, 0xfb, 0x93, 0x05, 0xf6, 0x68, 0x3a,
	0x54, 0xcb, 0xa6, 0x9c, 0xe5, 0x2d, 0x9b, 0x72, 0xa6, 0x58, 0x4f, 0x57, 0xa1, 0x47, 0x5a, 0x94,
	0x91, 0x12, 0xad, 0x8f, 0x8a, 0x75, 0x81, 0x3b, 0x24, 0x38, 0x12, 0x69, 0xd7, 0xb4, 0x54, 0xb1,
	0x56, 0x78, 0x05, 0xfd, 0x2a, 0x6b, 0xa6, 0x8a, 0xa7, 0xbf, 0x55, 0x23, 0x05, 0x38, 0xe8, 0x90,
	0x04, 0xcb, 0xa2, 0x91, 0x0a, 0x81, 0x9a, 0x9d, 0xf2, 0x3e, 0x3f, 0xa0, 0x42, 0x9e, 0x01, 0x2d,
	0xda, 0x50, 0xc1, 0x8c, 0x69, 0xf4, 0x55, 0x4f, 0x7d, 0x2a, 0x04, 0x69, 0x12, 0x62, 0x89, 0x9b,
	0x8c, 0x68, 0xc8, 0x55, 0x6f, 0x20, 0x28, 0x72, 0x3c, 0x5b, 0xca, 0x31, 0x82, 0xd9, 0xd6, 0x71,
	0x33, 0x32, 0x70, 0xf5, 0xb7, 0x4b, 0x61, 0x79, 0x08, 0xa8, 0x48, 0xd0, 0x73, 0x58, 0xa1, 0x39,
	0xc3, 0xfb, 0x19, 0x49, 0xf6, 0x0d, 0xbb, 0xde, 0x7c, 0x35, 0x64, 0x65, 0x91, 0x5f, 0x6f, 0x9b,
	0x8e, 0x48, 0xdc, 0x1f, 0x2d, 0xb0, 0x47, 0xb7, 0xa1, 0x3b, 0xaa, 0x6f, 0xf3, 0x10, 0x2a, 0x2b,
	0x1b, 0x53, 0x69, 0x25, 0x37, 0x40, 0x7b, 0x30, 0x6f, 0x08, 0xf0, 0xaf, 0x52, 0x52, 0x6e, 0xe7,
	0xfe, 0x5e, 0x85, 0xf9, 0x57, 0x71, 0xf5, 0x80, 0x9d, 0x66, 0x86, 0xd8, 0xe9, 0xff, 0xc4, 0x41,
	0x37, 0xa0, 0x6e, 0x6a, 0xe5, 0x87, 0x94, 0x6b, 0x16, 0xaa, 0x79, 0x60, 0x44, 0xfb, 0x94, 0xa3,
	0x6b, 0x00, 0xd9, 0x0d, 0xd3, 0xfa, 0x8c, 0x5e, 0x6a, 0x99, 0x44, 0xa9, 0x6f, 0x40, 0x3d, 0x95,
	0x94, 0x51, 0xd9, 0xd7, 0xfa, 0x85, 0xcc, 0xde, 0x88, 0xd4, 0x86, 0x6d, 0xf5, 0xa3, 0xcf, 0x64,
	0xc6, 0x4f, 0x18, 0x96, 0xad, 0x98, 0x77, 0x9d, 0xa5, 0xec, 0x6e, 0x17, 0x9a, 0x43, 0xa3, 0x40,
	0x57, 0x14, 0x27, 0x62, 0xe6, 0xeb, 0x62, 0xd8, 0xd9, 0x41, 0x95, 0xe0, 0xb1, 0x2a, 0x88, 0x0b,
	0x8b, 0x61, 0x2c, 0x7d, 0xec, 0x33, 0x1a, 0x1d, 0xe1, 0x36, 0x71, 0x56, 0x74, 0xe7, 0xd7, 0xc3,
	0x58, 0xee, 0x1d, 0x64, 0x22, 0xb4, 0x01, 0xf5, 0x84, 0x93, 0x20, 0xee, 0x26, 0x54, 0x0d, 0x2f,
	0x28, 0xdb, 0x51, 0x12, 0xa1, 0xcb, 0x50, 0x65, 0xa1, 0xdf, 0x62, 0xb8, 0x2d, 0x9c, 0x0b, 0x86,
	0x2e, 0xc3, 0x07, 0x6a, 0xa9, 0xa2, 0x53, 0xe1, 0x33, 0xd2, 0xc6, 0x41, 0xdf, 0x59, 0xd5, 0xa6,
	0x55, 0x2a, 0x0e, 0xf4, 0xba, 0xfc, 0x28, 0xad, 0x0d, 0x3f, 0x4a, 0x25, 0xfe, 0xbd, 0x38, 0xcc,
	0xbf, 0x87, 0x00, 0x09, 0x8f, 0x13, 0xc2, 0xa5, 0x22, 0xd4, 0x4b, 0xa7, 0x9b, 0xfe, 0x1a, 0x87,
	0x85, 0x49, 0xf6, 0xd4, 0x97, 0x7c, 0xa0, 0x7d, 0xa8, 0xb2, 0x38, 0xc0, 0x52, 0xc1, 0x70, 0xf4,
	0xc0, 0xb2, 0x39, 0xcd, 0xdf, 0x81, 0xd9, 0xef, 0x15, 0x96, 0xe8, 0x23, 0x35, 0x32, 0xf4, 0xe3,
	0x54, 0x3a, 0x97, 0xb5, 0x8f, 0xb7, 0xa7, 0xfa, 0xd0, 0xbb, 0x3d, 0x63, 0xa5, 0xda, 0x91, 0x7c,
	0x89, 0xbb, 0x09, 0x23, 0xc2, 0x59, 0xd7, 0xfd, 0x54, 0xac, 0xc7, 0xbf, 0x39, 0x57, 0x26, 0xbc,
	0x39, 0x5f, 0xc0, 0xb2, 0x2a, 0x0c, 0x96, 0xb4, 0xc9, 0x88, 0xff, 0x92, 0xca, 0x8e, 0x73, 0x55,
	0x67, 0xe9, 0x83, 0xa9, 0x59, 0xba, 0x57, 0xd8, 0x7d, 0x46, 0x65, 0x27, 0xcb, 0xd4, 0x52, 0x30,
	0x24, 0x5c, 0xbf, 0x0b, 0xcb, 0x23, 0xc9, 0x1c, 0x33, 0xdb, 0xac, 0x96, 0x67, 0x9b, 0x5a, 0x69,
	0x64, 0x59, 0xdf, 0x83, 0x0b, 0x63, 0xa2, 0x4c, 0x73, 0x51, 0x2d, 0x4f, 0x3d, 0x14, 0x56, 0x5f,
	0xd0, 0xe4, 0x9f, 0xf8, 0x39, 0x7f, 0xa8, 0x5e, 0x1f, 0xf3, 0x43, 0x45, 0x3f, 0x3c, 0x3b, 0xb0,
	0x36, 0x26, 0x94, 0x48, 0x14, 0x91, 0x99, 0x11, 0xd7, 0x8c, 0x59, 0x66, 0x68, 0xfd, 0x1a, 0x56,
	0x1f, 0x52, 0xf9, 0x5a, 0xfe, 0xd5, 0x60, 0x9e, 0xe7, 0x4a, 0xf1, 0x3c, 0x2b, 0xb4, 0x63, 0x82,
	0x4f, 0x46, 0xbb, 0xd5, 0x28, 0x7e, 0xe8, 0x97, 0x27, 0x70, 0x04, 0x30, 0xd7, 0xc2, 0xea, 0x62,
	0xdb, 0xe7, 0x50, 0x1d, 0xe6, 0x45, 0x1a, 0x04, 0x44, 0x08, 0xdb, 0xda, 0xba, 0x0d, 0x8b, 0x43,
	0xcd, 0x8b, 0x96, 0xa1, 0xde, 0x62, 0x58, 0xfa, 0x59, 0x0f, 0xdb, 0xe7, 0xd0, 0x2a, 0xd8, 0x9c,
	0x04, 0x29, 0x17, 0xb4, 0x47, 0x72, 0xa9, 0xb5, 0x15, 0x0c, 0x5e, 0xc5, 0xfc, 0xba, 0x2c, 0x43,
	0x9d, 0x86, 0xc4, 0x6f, 0xa6, 0x94, 0x49, 0x1a, 0xd9, 0xe7, 0x50, 0x15, 0x66, 0x53, 0x41, 0xb8,
	0x6d, 0x29, 0x1f, 0x39, 0xab, 0x15, 0xfa, 0x19, 0x74, 0x03, 0xae, 0x70, 0xd2, 0x22, 0x5c, 0x71,
	0x7e, 0xe8, 0x9f, 0xd8, 0x50, 0xf9, 0x64, 0xfb, 0xc5, 0xad, 0x36, 0x95, 0x9d, 0xb4, 0xa9, 0x32,
	0xb9, 0x63, 0x32, 0x9b, 0xff, 0xdd, 0x0e, 0x18, 0xdd, 0xe1, 0x49, 0xb0, 0x93, 0x67, 0xb9, 0x39,
	0xa7, 0xff, 0xf7, 0xf5, 0xfe, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x32, 0xe4, 0x70, 0xc1, 0x41,
	0x13, 0x00, 0x00,
}
